name: Deploy jekyll website on server
run-name: Website deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: Jekyll
  cancel-in-progress: false
jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Build jekyll site
        run: bundler exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Send the site via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_address }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./_site/
          server-dir: /public_html/
